trigger: none

pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- template: templates/yml/python/combo/setup-pip.yml@templates
- template: templates/yml/python/combo/run-pytest-ci.yml@templates
- template: templates/yml/any/sonar/run-sonar-cloud-cli-analysis.yml@templates
